version: '3.8'
services:
  php:
    container_name: "quarter_horse"
    image: php:8.1.16-apache
    volumes:
      - ./codigo/:/var/www/html/
    ports:
      - 824:80
  db:
    image: mariadb:10.5
    container_name: 'db_quarter_horse'
    restart:  always
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
  adminer:
    image: adminer:4.8.1
    container_name: "adminer_quarter_horse"
    restart: always
    ports:
      - 869:8080