-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 08:38:55 2024
-- Model: New Model	Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_quarter_horse` DEFAULT CHARACTER SET utf8 ;
USE `db_quarter_horse` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_cavalo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_quarter_horse`.`tb_cavalo` (
  `id_cavalo` INT NOT NULL AUTO_INCREMENT,
  `nome_cavalo` VARCHAR(45) NOT NULL,
  `raca_cavalo` VARCHAR(45) NOT NULL,
  `pelagem_cavalo` VARCHAR(45) NOT NULL,
  `premio_cavalo` VARCHAR(55) NOT NULL DEFAULT 'Nenhum',
  `situacao_cavalo` ENUM('Vendido', 'Disponível') NOT NULL DEFAULT 'Disponível',
  `img_cavalo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cavalo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_quarter_horse`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  `tipo_usuario` ENUM('usuario', 'familia') NOT NULL DEFAULT 'usuario',
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_quarter_horse`.`tb_lote` (
  `id_lote` INT NOT NULL AUTO_INCREMENT,
  `valor_lote` DECIMAL(10,2) NOT NULL,
  `data_lote` DATETIME NOT NULL,
  `estado_lote` ENUM('Em andamento', 'Expirado') NOT NULL DEFAULT 'Em andamento',
  `modalidade_cavalo` ENUM('Laço', 'Vaquejada', '3 Tambores', '-') NOT NULL DEFAULT '-',
  `modalidade_cavalo` INT NOT NULL,
  PRIMARY KEY (`id_lote`),
  INDEX `fk_tb_lote_tb_cavalo1_idx` (`modalidade_cavalo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_lote_tb_cavalo1`
	FOREIGN KEY (`modalidade_cavalo`)
	REFERENCES `mydb`.`tb_cavalo` (`id_cavalo`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_lance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_quarter_horse`.`tb_lance` (
  `id_lance` INT NOT NULL AUTO_INCREMENT,
  `valor_lance` DECIMAL(10,2) NOT NULL,
  `data_lance` DATETIME NOT NULL,
  `tb_usuario_id_usuario` INT NOT NULL,
  `tb_lote_id_lote` INT NOT NULL,
  PRIMARY KEY (`id_lance`),
  INDEX `fk_tb_lance_tb_usuario_idx` (`tb_usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_tb_lance_tb_lote1_idx` (`tb_lote_id_lote` ASC) VISIBLE,
  CONSTRAINT `fk_tb_lance_tb_usuario`
	FOREIGN KEY (`tb_usuario_id_usuario`)
	REFERENCES `mydb`.`tb_usuario` (`id_usuario`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_lance_tb_lote1`
	FOREIGN KEY (`tb_lote_id_lote`)
	REFERENCES `mydb`.`tb_lote` (`id_lote`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_pai_cavalo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_quarter_horse`.`tb_pai_cavalo` (
  `idtb_pai_cavalo` INT NOT NULL,
  PRIMARY KEY (`idtb_pai_cavalo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
